language: python
python:
  - 2.7
  - 3.5
sudo: false
env:
  - DB=SQLite
  - DB=Postgres
  - DB=MySQL
matrix:
  allow_failures:
    - env: DB=MySQL
services:
  - postgresql
  - mysql
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install -q flake8
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'create database my_db_test;'
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1';" -uroot
script:
#  - flake8 src/
  - if [ $DB == 'SQLite' ]; then (cd test/ && pybot SQLite3_DB_Tests.robot); fi
  - if [ $DB == 'Postgres' ]; then (cd test/ && pybot PostgreSQL_DB_Tests.robot); fi
  - if [ $DB == 'MySQL' ]; then (cd test/ && pybot MySQL_DB_Tests.robot); fi
