version: '3.1'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306'
  postgresqldb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - '5432'
  db2db:
    image: ibmcom/db2
    restart: always
    environment:
      LICENSE: accept
      DBNAME: mydb
      DB2INSTANCE: myuser
      DB2INST1_PASSWORD: mypass
    ports:
      - '50000'
